before_install:
- sudo apt-get -y update
- sudo apt-get -y install ruby ruby-dev make rpm rubygems curl
- gem install fpm --no-ri --no-rdoc
script:
- make

deploy:
  - provider: packagecloud
    repository: metrilyx
    username: metrilyx
    local-dir: build/ubuntu
    dist: ubuntu/trusty
    skip_cleanup: true
    token:
      secure: lgwlvLbyBZmUFIwdWIViI8SFQi/I0gSOmeVi/VKxHL3jRWsKG8mKyGLssO1Lw4y5ifdGQvQK+qo3iulkwfKUAmzfghwVxoMmYvasRcMJ/FWi/fy+3pVsU0rPZQN2fIRvb4ZKdCnfrlx/kzXePivCk27bS7d0giGFRd6MaMB5uwDYS1EHHOBlaQr1tc9dj+0zN5NO53fwUb8InomSKCzHXZKdqrsPj/jmlpsIHOuMEZbYiVRqy2zJ2utDJTROCnvdOFC90SqgFnxr4hBof3sunSs+9rTB/ycfCmzfswi9+FAPh56ArFH/Xq+VXxESMWGrnAGG/a6eyowA+vSp+bg4x52gtB7SntPzmA8qahHoDg6ZrRCfDdmbzrYIMvilHp+LdT1psUqw0qOSDwu4GmhHrZCfpxybl+RNKCAVzq8DkM2I4wKBoSFF3McTNL97jvgDH+7QcnRG93FubQ2aVsBqkGVbd/z0rCSainr3mE7s/09eqWf/OwRDxYA7U+EsiZt5nq0QF8YN8sgQjb0QUDTcm5jK50ah0U1pA+gmeitPXIPnA4TQslgZ1m0MK8hUpburBYvM+iowoOYYTEg39WHGvbaDhW53rHYLI3E/SgjMsUkZI1ClFO4lyy1m1rfPCBqT2wDN1rghlyNWXV6FvNiimoU1agPSlrUQ+FB0cqHq4nI=
  - provider: packagecloud
    repository: metrilyx
    username: metrilyx
    local-dir: build/el
    dist: el/7
    skip_cleanup: true
    token:
      secure: lgwlvLbyBZmUFIwdWIViI8SFQi/I0gSOmeVi/VKxHL3jRWsKG8mKyGLssO1Lw4y5ifdGQvQK+qo3iulkwfKUAmzfghwVxoMmYvasRcMJ/FWi/fy+3pVsU0rPZQN2fIRvb4ZKdCnfrlx/kzXePivCk27bS7d0giGFRd6MaMB5uwDYS1EHHOBlaQr1tc9dj+0zN5NO53fwUb8InomSKCzHXZKdqrsPj/jmlpsIHOuMEZbYiVRqy2zJ2utDJTROCnvdOFC90SqgFnxr4hBof3sunSs+9rTB/ycfCmzfswi9+FAPh56ArFH/Xq+VXxESMWGrnAGG/a6eyowA+vSp+bg4x52gtB7SntPzmA8qahHoDg6ZrRCfDdmbzrYIMvilHp+LdT1psUqw0qOSDwu4GmhHrZCfpxybl+RNKCAVzq8DkM2I4wKBoSFF3McTNL97jvgDH+7QcnRG93FubQ2aVsBqkGVbd/z0rCSainr3mE7s/09eqWf/OwRDxYA7U+EsiZt5nq0QF8YN8sgQjb0QUDTcm5jK50ah0U1pA+gmeitPXIPnA4TQslgZ1m0MK8hUpburBYvM+iowoOYYTEg39WHGvbaDhW53rHYLI3E/SgjMsUkZI1ClFO4lyy1m1rfPCBqT2wDN1rghlyNWXV6FvNiimoU1agPSlrUQ+FB0cqHq4nI=

notifications:
  slack:
    rooms:
    - ticketmaster:E5CXbILXq45Y5LYcsO8BD3B3#metrilyx
